### ISSUE TITLE
What is not possible

### ISSUE THREAD

**Issue by feth** [eyssette/mindmap#2]
Both those "missing" functions are not advertised as an impairment but as a way to reduce antagonistic interactions:

## Search

On some mastodon instances you cannot search words (but hashtags); on some you can search among your own toots; on some you can search in all toots.

## quote toot

No. But there is a miniature if you put the URL of a toot.

**Comment by eyssette** [comment]
Thanks for your comment on my [‘Join Mastodon' mindmap](https://github.com/eyssette/mindmap/blob/main/mastodon-EN.md). You're right to point out these differences between Twitter and Mastodon.
